import logging
from typing import TYPE_CHECKING

from github import Auth, Github

from ..security.leak_detector import LeakDetector

if TYPE_CHECKING:
    from ..analysis.analyzer import RCAReport

logger = logging.getLogger(__name__)


def post_pr_comment(
    github_token: str,
    repository: str,
    pr_number: int,
    report: "RCAReport",
) -> None:
    """Post RCA report as a comment on a GitHub PR.

    Args:
        github_token: GitHub personal access token
        repository: Repository in format "owner/repo"
        pr_number: PR number
        report: RCA report object

    Raises:
        Exception: If posting comment fails
    """
    logger.info(f"Posting comment to {repository}#{pr_number}")

    auth = Auth.Token(github_token)
    g = Github(auth=auth)

    try:
        repo = g.get_repo(repository)
        pr = repo.get_pull(pr_number)

        # Use the same detailed format as the job summary
        # Note: to_markdown() already includes the "Generated by" footer
        comment_body = report.to_markdown()

        # Final safety check: sanitize comment body
        leak_detector = LeakDetector()
        sanitized_comment = leak_detector.sanitize_text(comment_body)

        pr.create_issue_comment(sanitized_comment)
        logger.info("Comment posted successfully")

    finally:
        g.close()
